#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Hack Nerd Font:Regular:14.0"
yabai -m config status_bar_icon_font         "Hack Nerd Font:Regular:14.0"
yabai -m config status_bar_background_color  0xff2E3440
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip           6 7 8
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        |
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff4C566A
yabai -m config normal_window_border_color   0xff2E3440
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.60
# yabai -m config window_opacity_duration      0.0
# yabai -m config window_border_placement      interior
# yabai -m config window_border_radius         -1.0
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   8

# rules for apps
yabai -m rule --add app="^iTerm$" space=2
yabai -m rule --add app="^Workspace$" space=3
yabai -m rule --add app=Mail space=3
yabai -m rule --add app=Telegram space=4
yabai -m rule --add app="^WhastApp$" space=4
yabai -m rule --add app=Spotify space=5

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Preview$" manage=off border=off
yabai -m rule --add app="^Picture in Picture$" manage=off
# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
